# Use root/example as user/password credentials
version: '3.5'

services:
  mongo:
    container_name: quickurl_mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - quick_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: quickurl_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - quick_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  quick_network:
    name: quickurl_network